### ISSUE TITLE
issues about redirect between webs

### ISSUE THREAD

**Issue by juicyali** [schmunk42/docker-nginx-redirect#14]
Greetings!
I am trying to set an online viewer of books and pics. 
Work layout likes:
1. list links.
2. people hit links and target to purchase webs.
3. people direct to webs of pics or books to read online.
4. purchase lock with their devices or IPs.

I dont know its too complex or what. but its really mass for me. May you help me this?

Thank you!

**Comment by schmunk42** [comment]
How is this related to this repo?
