### ISSUE TITLE
http redirect instead of https

### ISSUE THREAD

**Issue by martinvw** [schmunk42/docker-nginx-redirect#3]
Hello,

I use this docker image to redirect visitors from my www subdomain to my main website and combined it with jwilder/nginx-proxy and jrcs/letsencrypt-nginx-proxy-companion.

However my https://www.martinvw.nl now redirects to http://martinvw.nl which redirect to https://martinvw.nl. Ideally it should directly do the proper redirect, do you have any suggestions or are you open to receive a PR where I also make the `$scheme` configurable?

Thanks!

**Comment by schmunk42** [comment]
Sure, PRs are very welcome!
